### ISSUE TITLE
Autolink support without <...>

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark-extras#12]
See https://github.com/thephpleague/commonmark/issues/308

**Comment by tankerkiller125** [comment]
Have a look at https://github.com/OSSchools/commonmark-ext/blob/master/src/InlineParsers/AutoLinkParser.php to see how I've done this. You can pretty much copy it although you'll need to remove the URLMeta stuff (automatic titling of links based on webpage title)

**Comment by glensc** [comment]
@tankerkiller125 `OSSchools/commonmark-ext` seems to do too much and adding unwanted dependencies:
- `laravel/framework`
- `mpratt/embera`

I don't want markdown rendering library have code to fetch remotes via curl. violates single responsibility principle.

**Comment by glensc** [comment]
@colinodell maybe you want(can, please!?:) to create single purpose supported version under `thephpleague` to handle this kind of problem, like you did for [`thephpleague/commonmark-ext-smartpunct`](https://github.com/thephpleague/commonmark-ext-smartpunct) and [`thephpleague/commonmark-ext-inlines-only`](https://github.com/thephpleague/commonmark-ext-inlines-only)

i have this in checklist to transition to commonmark:
- https://github.com/eventum/eventum/pull/501#issue-259789541

**Comment by colinodell** [comment]
Yep I will work on creating this.  I'll either be following @markcarver's suggestion or  https://github.com/thephpleague/commonmark/issues/345 if that seems to be viable

**Comment by glensc** [comment]
I think the big end goal would be to have GFM (GitHub Flavored Markdown / GitLab Flavored Markdown) enable-able with single extension:
- https://github.github.com/gfm/
- https://docs.gitlab.com/ee/user/markdown.html

currently picking features one by one while just want what people are accustomed for, and that's GFM!

**Comment by tankerkiller125** [comment]
@glensc That package was designed specifically for the core project they were built, hence the Laravel requirements and other requirements. The actual code for the auto-linking however did not require those extra dependencies.

**Comment by colinodell** [comment]
This has been implemented via https://github.com/thephpleague/commonmark-ext-autolink/blob/v0.1.0/src/AutolinkExtension.php.  We'll pull it into here as a dependency.
