### ISSUE TITLE
New sub-package: emoji

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark-extras#19]
A community extension already exists for emoji, but it's tightly coupled to Laravel and Github: https://packagist.org/packages/alt-three/emoji

Let's create a generic version which renders `:emoji:` input as Unicode emoji characters (and maybe bundle in some custom renderers which can render them as images?)

**Comment by GrahamCampbell** [comment]
It's not tightly coupled to laravel (apart from the require in the composer, which could be removed), and it's not coupled to github either actually - the parser just expects some abstract repository: https://github.com/AltThree/Emoji/blob/v7.0.0/src/EmojiParser.php.

**Comment by GrahamCampbell** [comment]
All of the things are meshed together in https://github.com/AltThree/Emoji/blob/v7.0.0/src/EmojiServiceProvider.php, and the rest of the package is decoupled.

**Comment by GrahamCampbell** [comment]
I'd be interested in getting emoji build right into the official extras package. The latest version is now at https://github.com/CachetHQ/Emoji, but has not been tagged yet. I'd like to be able to abandon both https://github.com/CachetHQ/Emoji and https://github.com/CachetHQ/Twitter in favour of official packages.

---

Maybe we should chat about this in private. Can I instant message you somewhere?

**Comment by colinodell** [comment]
Hi Graham,

That sounds good to me!  Feel free to DM me on Twitter or Google Hangouts (or whatever Google is calling their messaging platform these days)

**Comment by colinodell** [comment]
Moving this to https://github.com/thephpleague/commonmark/issues/421
