### ISSUE TITLE
carry lossendae/commonmark-task-lists

### ISSUE THREAD

**Issue by glensc** [thephpleague/commonmark-extras#22]
the extension is useful creating github/gitlab style task lists.

however, it's not maintained: https://github.com/lossendae/commonmark-task-lists/pull/1

could this be carried to this organization to get some support? 

personally, I can't update beyond 0.18 because of that extension reliance

**Comment by colinodell** [comment]
We recently added a task list extension: https://github.com/thephpleague/commonmark-ext-task-list Perhaps we could ask that maintainer if they would like to mark theirs as abandoned and recommend ours instead?

**Comment by lossendae** [comment]
Hello, I'll archive my old unmaintained extension and link to the new one. Thanks.

**Comment by glensc** [comment]
@lossendae seems you did not get what abandoned means, you need to mark project in packagist as abandoned and provide superseding package:
- https://packagist.org/packages/lossendae/commonmark-task-lists

as you archived your github project, I can not comment there.

**Comment by lossendae** [comment]
I indeed did not know. Thanks for the pointer.
