### ISSUE TITLE
Strikethrough support

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark-extras#6]
Input:

``` md
~~text~~
```

Output:

``` html
<del>text</del>
```

Note that this is NOT part of the CommonMark spec, and NOT an officially-supported feature of league/commonmark.  However, it's a feature some folks might use and its implementation would be a good example of how to write these types of customizations, which is why I'd like to include it here.

**Comment by tankerkiller125** [comment]
See #13 for a solution for this, however this pull request still needs the test however

**Comment by colinodell** [comment]
An ["official" strikethrough extension](https://github.com/thephpleague/commonmark-ext-strikethrough) has been created and will be added here via #21
